### ISSUE TITLE
can/should we use ubuntu 16.04.1 LTS?

### ISSUE THREAD

**Issue by cezarneaga** [carlalexander/debops-wordpress#89]
Hi Carl,

was wondering if we are to upgrade ubuntu if everything would work well or if you could use some help testing on this?

Cezar

**Comment by blindpet** [comment]
Ubuntu 16 broke Varnish for me (seems a problem with Ubuntu package) and I had to force an install from the official Varnish jessie repo to get it working.

**Comment by carlalexander** [comment]
Hey @cezarneaga! I've done a few test runs of it, but I welcome more testing of course! By default, migrating to Xenial might break a few things. Varnish seems to do ok if you remove the old version and reinstall from the Ubuntu repo.

So far, my migration process looks kinda like this:
1. Upgrade to Xenial.
2. `sudo apt-get remove hhvm` to remove HHVM.
3. `sudo apt-get remove varnish` to remove Varnish. You might need to remove the upstream repo as well.
4. Run `debops -u root` to refresh the basic configuration in case something broke.
5. Run `debops wordpress -u root` to install PHP7, Xenial Varnish and update the configs.

I _strongly_ recommend doing a snapshot of your droplet or machine if you can before starting.

**Comment by cezarneaga** [comment]
Thanks @blindpet & @carlalexander!
Will try this out and get back to you

C

**Comment by carlalexander** [comment]
I migrated my site to a Xenial server yesterday. Everything works fine! The performance improvements from HTTP/2 are impressive. 

I couldn't run a migration because I was moving from a RapidSSL certificate to Let's Encrypt. This isn't an easy migration to do so I decided to build a server from scratch instead. I fixed a few issues, but everything worked well. I'll probably tag a version soon.

**Comment by tobeycodes** [comment]
I will try it on a few of my sites this week

**Comment by cezarneaga** [comment]
sound very exciting @carlalexander!
did you run the new build from current master? i see the last commits were on it.
eager to give it a try.

**Comment by carlalexander** [comment]
I ran it off master @cezarneaga

**Comment by cezarneaga** [comment]
did you get into this error by any chance? on running debops?

```
TASK [debops.ntp : Configure timezone with timedatectl] ************************
fatal: []: FAILED! => {"changed": true, "cmd": "timedatectl set-timezone ", "delta": "0:00:00.004680", "end": "2016-08-24 08:58:11.709015", "failed": true, "rc": 1, "start": "2016-08-24 08:58:11.704335", "stderr": "Invalid number of arguments.", "stdout": "", "stdout_lines": [], "warnings": []}
```

saw a previous discussion relating i think to this. restarted apparmor but still getting the same.
Cheers,
C
PS: this is on digital ocean, 16.04

**Comment by carlalexander** [comment]
I haven't seen this issue before @cezarneaga. Does it happen every time?

**Comment by cezarneaga** [comment]
yes. tried it several times. the only variable that changed is that i am now running mac os sierra.

**Comment by carlalexander** [comment]
Let me give it a try today and see

**Comment by carlalexander** [comment]
I can confirm I have the issue now with the same code I used this weekend. The only thing that might have changed is `debops-update`. I'm not sure if I ran it before I used it last weekend. Have you seen this issue with `debops.ntp` @drybjed?

**Comment by carlalexander** [comment]
Nevermind, I found the issue. `ntp_timezone` changed to `ntp__timezone`.

**Comment by drybjed** [comment]
@carlalexander On Ubuntu hosts, [systemd-timesyncd is used by default now](https://github.com/debops/ansible-ntp/commit/be053282e890538c2f23c14b5e05e60e6c0d9831) if you haven't noticed.

**Comment by carlalexander** [comment]
Yeah, but the issue was that I hadn't updated DebOps recently enough. You renamed the variable so it broke that task lol. If anything, that might be a bug because that means that the default value for `ntp__timezone` doesn't work with `timedatectl`.

I pushed a commit with the change @cezarneaga. Worked fine just now.

**Comment by cezarneaga** [comment]
@carlalexander Indeed, it passed second command: `debops`.
on last one i got:

```
RUNNING HANDLER [debops.fail2ban : Restart fail2ban] ***************************
fatal: [....]: FAILED! => {"changed": false, "failed": true, "msg": "Job for fail2ban.service failed because the control process exited with error code. See \"systemctl status fail2ban.service\" and \"journalctl -xe\" for details.\n"}
```

running it again just to see if persists.

C

**Comment by cezarneaga** [comment]
second time it went through! :) but no wp. just default nginx welcome page

**Comment by drybjed** [comment]
@cezarneaga Second time it passed because the handler that restarts `fail2ban` wasn't activated. Can you check in the logs what the error might be?

**Comment by cezarneaga** [comment]
@drybjed can you point me to the right destination? do you mean server side or local? i am on mac os.

**Comment by cezarneaga** [comment]
do you mean on server /var/log/fail2ban.log ?

**Comment by cezarneaga** [comment]
```
iptables -w -X f2b-sshd -- stderr: b"iptables v1.6.0: Couldn't load target `f2b-sshd':No such file or directory\n\nTry `iptables -h' or 'iptables --help' for more information.\niptables: No chain/target/match by that name.\niptables: No chain/target/match by that name.\n"
2016-08-25 13:18:03,447 fail2ban.action         [29019]: ERROR   iptables -w -D INPUT -p tcp -m multiport --dports ssh -j f2b-sshd
iptables -w -F f2b-sshd
iptables -w -X f2b-sshd -- returned 1
2016-08-25 13:18:03,448 fail2ban.actions        [29019]: ERROR   Failed to execute unban jail 'sshd' action 'iptables-multiport' info '{'ip': '122.169.107.77', 'failures': 5, 'time': 1472130864.7553291, 'matches': 'Aug 25 13:05:29 digitalocean sshd[5637]: Invalid user trade from 122.169.107.77Aug 25 13:05:29 digitalocean sshd[5637]: pam_unix(sshd:auth): authentication failure; logname= uid=0 euid=0 tty=ssh ruser= rhost=122.169.107.77Aug 25 13:05:31 digitalocean sshd[5637]: Failed password for invalid user trade from 122.169.107.77 port 51180 ssh2Aug 25 13:05:33 digitalocean sshd[5637]: Failed password for invalid user trade from 122.169.107.77 port 51180 ssh2Aug 25 13:05:36 digitalocean sshd[5637]: Failed password for invalid user trade from 122.169.107.77 port 51180 ssh2'}': Error stopping action
2016-08-25 13:18:03,551 fail2ban.action         [29019]: ERROR   iptables -w -D INPUT -p tcp -m multiport --dports ssh -j f2b-sshd
iptables -w -F f2b-sshd
iptables -w -X f2b-sshd -- stdout: b''
2016-08-25 13:18:03,551 fail2ban.action         [29019]: ERROR   iptables -w -D INPUT -p tcp -m multiport --dports ssh -j f2b-sshd
iptables -w -F f2b-sshd
iptables -w -X f2b-sshd -- stderr: b"iptables v1.6.0: Couldn't load target `f2b-sshd':No such file or directory\n\nTry `iptables -h' or 'iptables --help' for more information.\niptables: No chain/target/match by that name.\niptables: No chain/target/match by that name.\n"
2016-08-25 13:18:03,552 fail2ban.action         [29019]: ERROR   iptables -w -D INPUT -p tcp -m multiport --dports ssh -j f2b-sshd
iptables -w -F f2b-sshd
iptables -w -X f2b-sshd -- returned 1
2016-08-25 13:18:03,552 fail2ban.actions        [29019]: ERROR   Failed to stop jail 'sshd' action 'iptables-multiport': Error stopping action
2016-08-25 13:18:03,552 fail2ban.jail           [29019]: INFO    Jail 'sshd' stopped
2016-08-25 13:18:03,563 fail2ban.server         [29019]: INFO    Exiting Fail2ban
```

**Comment by drybjed** [comment]
@cezarneaga Hmm, not sure what might cause these errors, although I don't use `fail2ban` that often. What happens if you try to restart the `fail2ban` service?

**Comment by cezarneaga** [comment]
```
[....] Restarting fail2ban (via systemctl): fail2ban.serviceJob for fail2ban.service failed because the control process exited with error code. See "systemctl status fail2ban.service" and "journalctl -xe" for details.
 failed!
```

**Comment by cezarneaga** [comment]
:) its always different! :)

reset the machine, started from scratch. now new error:

```
TASK [debops.mariadb : Install database client packages] ***********************
failed: [...] (item=[u'python-mysqldb', u'mariadb-client']) => {"cache_update_time": 0, "cache_updated": false, "failed": true, "item": ["python-mysqldb", "mariadb-client"], "msg": "'/usr/bin/apt-get -y -o \"Dpkg::Options::=--force-confdef\" -o \"Dpkg::Options::=--force-confold\"     install 'mariadb-client' -o APT::Install-Recommends=no' failed: E: Sub-process /usr/bin/dpkg returned an error code (2)\n", "stderr": "E: Sub-process /usr/bin/dpkg returned an error code (2)\n", "stdout": "Reading package lists...\nBuilding dependency tree...\nReading state information...\nThe following packages were automatically installed and are no longer required:\n  laptop-detect os-prober\nUse 'sudo apt autoremove' to remove them.\nThe following NEW packages will be installed:\n  mariadb-client\n0 upgraded, 1 newly installed, 0 to remove and 9 not upgraded.\nNeed to get 13.0 kB of archives.\nAfter this operation, 61.4 kB of additional disk space will be used.\nGet:1 http://security.ubuntu.com/ubuntu xenial-security/universe amd64 mariadb-client all 10.0.25-0ubuntu0.16.04.1 [13.0 kB]\nFetched 13.0 kB in 0s (234 kB/s)\ndpkg: error: dpkg status database is locked by another process\r\n", "stdout_lines": ["Reading package lists...", "Building dependency tree...", "Reading state information...", "The following packages were automatically installed and are no longer required:", "  laptop-detect os-prober", "Use 'sudo apt autoremove' to remove them.", "The following NEW packages will be installed:", "  mariadb-client", "0 upgraded, 1 newly installed, 0 to remove and 9 not upgraded.", "Need to get 13.0 kB of archives.", "After this operation, 61.4 kB of additional disk space will be used.", "Get:1 http://security.ubuntu.com/ubuntu xenial-security/universe amd64 mariadb-client all 10.0.25-0ubuntu0.16.04.1 [13.0 kB]", "Fetched 13.0 kB in 0s (234 kB/s)", "dpkg: error: dpkg status database is locked by another process"]}

NO MORE HOSTS LEFT *************************************************************
```

**Comment by cezarneaga** [comment]
and most of the time a second run solves it. ran debops wordpress a second time. all is good and you were right. the speed is bonkers. 💯

**Comment by drybjed** [comment]
@cezarneaga I would gues that the above error happened, because DebOps installs `apticron` among other things. By a random chance, an APT update script was started from `cron` at this point in the playbook, and Ansible couldn't use the APT to install packages at the same time.

**Comment by blindpet** [comment]
For future reference you get debug info from fail2ban like this

`sudo fail2ban-client -d`

**Comment by carlalexander** [comment]
I setup a machine yesterday to test something for @schrapel and I didn't encounter this problem with fail2ban. Are we seeing this issue consistently?

**Comment by cezarneaga** [comment]
i setup another one too and got the error no more :)

**Comment by carlalexander** [comment]
Cool, I'll close it and we'll reopen if we see it again! 😄

**Comment by zedrickvillas** [comment]
Encountered this error.
Rebuilt my droplet, ran the installation, encountered again the fail2ban error, ran the debops wordpress again, this time it was successful but when i access the site the nginx welcome page displays.

Should i do it again? 😭
